version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - run: bundle install
      - run:
        name: ruby test
        command: bundle exec rspec