version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_DB: stop_sweets_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    environment:
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
      DATABASE_PASSWORD: postgres
    steps:
      - checkout
      - restore_cache:
          key: Gemfile-v1-{{ checksum "Gemfile.lock" }}
      - run:
          name: プロジェクトローカルにGemをインストールするよう設定
          command: bundle config set --local path 'vendor/bundle'
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.2.11
            bundle install --jobs=4 --retry=3
      - run: yarn install
      - save_cache:
          key: Gemfile-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: run tests
          command: bundle exec rspec

  deploy:
    docker:
      - image: circleci/ruby:2.7.2-node
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.2.11
            bundle install --jobs=4 --retry=3
      - add_ssh_keys:
          fingerprints: "23:3a:d8:a5:c8:eb:64:f9:3f:aa:d8:0b:0d:60:fa:50"
      - run: export DATABASE_PASSWORD=postgres
      - run:
          name: Capistrano deploy
          command: bundle exec cap production deploy

workflows:
  version: 2.1
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build