version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_DB: stop_sweets_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    environment:
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
      DATABASE_PASSWORD: postgres
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - checkout
      - restore_cache:
          key: Gemfile-v1-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: Gemfile-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: ruby test
          command: bundle exec rspec