version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
      - image: circleci/postgres:13.2
       environment:
          POSTGRES_DB: stop_sweets_test
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - restore_cache:
          key: Gemfile-v1-{{ checksum "Gemfile.lock" }}
      - run: bundle install
      - save_cache:
          key: Gemfile-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor
      - run:
          name: ruby test
          command: bundle exec rspec